service: movie-app-be
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: prod
  httpApi:
    cors: true

functions:
  graphql:
    handler: src/index.handler

    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET

    environment:
      DB_MONGO: arn:aws:secretsmanager:us-east-1:039297709667:secret:movie-app-mongo-qJPRHv
      SECRET: arn:aws:secretsmanager:us-east-1:039297709667:secret:movie-app-secret-word-BqyyYF
      OMDB_API_KEY: arn:aws:secretsmanager:us-east-1:039297709667:secret:movie-app-api-key-lmyyzk

plugins:
  - serverless-offline
